pipeline {
agent any



stages {
stage ('Compile Stage') {



steps {
withMaven(maven :'apache-maven-3.6.3-bin') {
bat 'mvn -f Exit_Test/pom.xml clean compile'
}
}
}
stage ('Testing Stage') {



steps {
withMaven(maven :'apache-maven-3.6.3-bin') {
bat 'mvn -f Exit_Test/pom.xml test'
}
}
}
}
}
